// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ItemPickedNotify.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Net.Proto {

  /// <summary>Holder for reflection information generated from ItemPickedNotify.proto</summary>
  public static partial class ItemPickedNotifyReflection {

    #region Descriptor
    /// <summary>File descriptor for ItemPickedNotify.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ItemPickedNotifyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZJdGVtUGlja2VkTm90aWZ5LnByb3RvEgJwYhoMRGVmaW5lLnByb3RvIowB",
            "ChBJdGVtUGlja2VkTm90aWZ5Eg4KBkl0ZW1JRBgBIAEoCRIfCgRJbmZvGAIg",
            "ASgLMhEucGIuSXRlbUJhc2ljSW5mbxIPCgdTY2VuZUlEGAMgASgFEhYKDlRp",
            "bWVTdGFtcE1pY3JvGAQgASgDEh4KCFBvc2l0aW9uGAUgASgLMgwucGIuVmVj",
            "dG9yMkRCEloEL2NtZKoCCU5ldC5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Net.Proto.DefineReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Net.Proto.ItemPickedNotify), global::Net.Proto.ItemPickedNotify.Parser, new[]{ "ItemID", "Info", "SceneID", "TimeStampMicro", "Position" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ItemPickedNotify : pb::IMessage<ItemPickedNotify>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ItemPickedNotify> _parser = new pb::MessageParser<ItemPickedNotify>(() => new ItemPickedNotify());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ItemPickedNotify> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Net.Proto.ItemPickedNotifyReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemPickedNotify() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemPickedNotify(ItemPickedNotify other) : this() {
      itemID_ = other.itemID_;
      info_ = other.info_ != null ? other.info_.Clone() : null;
      sceneID_ = other.sceneID_;
      timeStampMicro_ = other.timeStampMicro_;
      position_ = other.position_ != null ? other.position_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemPickedNotify Clone() {
      return new ItemPickedNotify(this);
    }

    /// <summary>Field number for the "ItemID" field.</summary>
    public const int ItemIDFieldNumber = 1;
    private string itemID_ = "";
    /// <summary>
    ///ItemID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ItemID {
      get { return itemID_; }
      set {
        itemID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Info" field.</summary>
    public const int InfoFieldNumber = 2;
    private global::Net.Proto.ItemBasicInfo info_;
    /// <summary>
    ///基本信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Net.Proto.ItemBasicInfo Info {
      get { return info_; }
      set {
        info_ = value;
      }
    }

    /// <summary>Field number for the "SceneID" field.</summary>
    public const int SceneIDFieldNumber = 3;
    private int sceneID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SceneID {
      get { return sceneID_; }
      set {
        sceneID_ = value;
      }
    }

    /// <summary>Field number for the "TimeStampMicro" field.</summary>
    public const int TimeStampMicroFieldNumber = 4;
    private long timeStampMicro_;
    /// <summary>
    ///拾取的时间戳(微秒)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TimeStampMicro {
      get { return timeStampMicro_; }
      set {
        timeStampMicro_ = value;
      }
    }

    /// <summary>Field number for the "Position" field.</summary>
    public const int PositionFieldNumber = 5;
    private global::Net.Proto.Vector2D position_;
    /// <summary>
    ///位置
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Net.Proto.Vector2D Position {
      get { return position_; }
      set {
        position_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ItemPickedNotify);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ItemPickedNotify other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ItemID != other.ItemID) return false;
      if (!object.Equals(Info, other.Info)) return false;
      if (SceneID != other.SceneID) return false;
      if (TimeStampMicro != other.TimeStampMicro) return false;
      if (!object.Equals(Position, other.Position)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ItemID.Length != 0) hash ^= ItemID.GetHashCode();
      if (info_ != null) hash ^= Info.GetHashCode();
      if (SceneID != 0) hash ^= SceneID.GetHashCode();
      if (TimeStampMicro != 0L) hash ^= TimeStampMicro.GetHashCode();
      if (position_ != null) hash ^= Position.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ItemID.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ItemID);
      }
      if (info_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Info);
      }
      if (SceneID != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(SceneID);
      }
      if (TimeStampMicro != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(TimeStampMicro);
      }
      if (position_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Position);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ItemID.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ItemID);
      }
      if (info_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Info);
      }
      if (SceneID != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(SceneID);
      }
      if (TimeStampMicro != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(TimeStampMicro);
      }
      if (position_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Position);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ItemID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ItemID);
      }
      if (info_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Info);
      }
      if (SceneID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SceneID);
      }
      if (TimeStampMicro != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TimeStampMicro);
      }
      if (position_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Position);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ItemPickedNotify other) {
      if (other == null) {
        return;
      }
      if (other.ItemID.Length != 0) {
        ItemID = other.ItemID;
      }
      if (other.info_ != null) {
        if (info_ == null) {
          Info = new global::Net.Proto.ItemBasicInfo();
        }
        Info.MergeFrom(other.Info);
      }
      if (other.SceneID != 0) {
        SceneID = other.SceneID;
      }
      if (other.TimeStampMicro != 0L) {
        TimeStampMicro = other.TimeStampMicro;
      }
      if (other.position_ != null) {
        if (position_ == null) {
          Position = new global::Net.Proto.Vector2D();
        }
        Position.MergeFrom(other.Position);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ItemID = input.ReadString();
            break;
          }
          case 18: {
            if (info_ == null) {
              Info = new global::Net.Proto.ItemBasicInfo();
            }
            input.ReadMessage(Info);
            break;
          }
          case 24: {
            SceneID = input.ReadInt32();
            break;
          }
          case 32: {
            TimeStampMicro = input.ReadInt64();
            break;
          }
          case 42: {
            if (position_ == null) {
              Position = new global::Net.Proto.Vector2D();
            }
            input.ReadMessage(Position);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ItemID = input.ReadString();
            break;
          }
          case 18: {
            if (info_ == null) {
              Info = new global::Net.Proto.ItemBasicInfo();
            }
            input.ReadMessage(Info);
            break;
          }
          case 24: {
            SceneID = input.ReadInt32();
            break;
          }
          case 32: {
            TimeStampMicro = input.ReadInt64();
            break;
          }
          case 42: {
            if (position_ == null) {
              Position = new global::Net.Proto.Vector2D();
            }
            input.ReadMessage(Position);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
