// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ItemStatusUpdate.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Net.Proto {

  /// <summary>Holder for reflection information generated from ItemStatusUpdate.proto</summary>
  public static partial class ItemStatusUpdateReflection {

    #region Descriptor
    /// <summary>File descriptor for ItemStatusUpdate.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ItemStatusUpdateReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZJdGVtU3RhdHVzVXBkYXRlLnByb3RvEgJwYhoMRGVmaW5lLnByb3RvIvIC",
            "ChBJdGVtU3RhdHVzVXBkYXRlEjcKClVwZGF0ZVR5cGUYASABKA4yIy5wYi5J",
            "dGVtU3RhdHVzVXBkYXRlLkl0ZW1VcGRhdGVUeXBlEh8KBEluZm8YAiABKAsy",
            "ES5wYi5JdGVtQmFzaWNJbmZvEi8KDk1vdmVtZW50U3RhdHVzGAMgASgLMhcu",
            "cGIuQmFzaWNNb3ZlbWVudFN0YXR1cxIPCgdTY2VuZUlEGAQgASgFEi0KBVN0",
            "YXRlGAUgASgOMh4ucGIuSXRlbVN0YXR1c1VwZGF0ZS5JdGVtU3RhdGUSEAoI",
            "T3duZXJVSUQYBiABKA0SEAoIVHNNaWxsaXMYByABKAQiOwoJSXRlbVN0YXRl",
            "EggKBElkbGUQABIKCgZBY3RpdmUQARIKCgZQaWNrZWQQAhIMCghEaXNhYmxl",
            "ZBADIjIKDkl0ZW1VcGRhdGVUeXBlEgkKBVNwYXduEAASCwoHRGVzdHJveRAB",
            "EggKBE1vdmUQAkISWgQvY21kqgIJTmV0LlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Net.Proto.DefineReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Net.Proto.ItemStatusUpdate), global::Net.Proto.ItemStatusUpdate.Parser, new[]{ "UpdateType", "Info", "MovementStatus", "SceneID", "State", "OwnerUID", "TsMillis" }, null, new[]{ typeof(global::Net.Proto.ItemStatusUpdate.Types.ItemState), typeof(global::Net.Proto.ItemStatusUpdate.Types.ItemUpdateType) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ItemStatusUpdate : pb::IMessage<ItemStatusUpdate>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ItemStatusUpdate> _parser = new pb::MessageParser<ItemStatusUpdate>(() => new ItemStatusUpdate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ItemStatusUpdate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Net.Proto.ItemStatusUpdateReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemStatusUpdate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemStatusUpdate(ItemStatusUpdate other) : this() {
      updateType_ = other.updateType_;
      info_ = other.info_ != null ? other.info_.Clone() : null;
      movementStatus_ = other.movementStatus_ != null ? other.movementStatus_.Clone() : null;
      sceneID_ = other.sceneID_;
      state_ = other.state_;
      ownerUID_ = other.ownerUID_;
      tsMillis_ = other.tsMillis_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ItemStatusUpdate Clone() {
      return new ItemStatusUpdate(this);
    }

    /// <summary>Field number for the "UpdateType" field.</summary>
    public const int UpdateTypeFieldNumber = 1;
    private global::Net.Proto.ItemStatusUpdate.Types.ItemUpdateType updateType_ = global::Net.Proto.ItemStatusUpdate.Types.ItemUpdateType.Spawn;
    /// <summary>
    ///更新类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Net.Proto.ItemStatusUpdate.Types.ItemUpdateType UpdateType {
      get { return updateType_; }
      set {
        updateType_ = value;
      }
    }

    /// <summary>Field number for the "Info" field.</summary>
    public const int InfoFieldNumber = 2;
    private global::Net.Proto.ItemBasicInfo info_;
    /// <summary>
    ///物品基本信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Net.Proto.ItemBasicInfo Info {
      get { return info_; }
      set {
        info_ = value;
      }
    }

    /// <summary>Field number for the "MovementStatus" field.</summary>
    public const int MovementStatusFieldNumber = 3;
    private global::Net.Proto.BasicMovementStatus movementStatus_;
    /// <summary>
    ///运动状态
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Net.Proto.BasicMovementStatus MovementStatus {
      get { return movementStatus_; }
      set {
        movementStatus_ = value;
      }
    }

    /// <summary>Field number for the "SceneID" field.</summary>
    public const int SceneIDFieldNumber = 4;
    private int sceneID_;
    /// <summary>
    ///场景信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SceneID {
      get { return sceneID_; }
      set {
        sceneID_ = value;
      }
    }

    /// <summary>Field number for the "State" field.</summary>
    public const int StateFieldNumber = 5;
    private global::Net.Proto.ItemStatusUpdate.Types.ItemState state_ = global::Net.Proto.ItemStatusUpdate.Types.ItemState.Idle;
    /// <summary>
    /// 权威状态
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Net.Proto.ItemStatusUpdate.Types.ItemState State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    /// <summary>Field number for the "OwnerUID" field.</summary>
    public const int OwnerUIDFieldNumber = 6;
    private uint ownerUID_;
    /// <summary>
    /// 触发/拾取者
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint OwnerUID {
      get { return ownerUID_; }
      set {
        ownerUID_ = value;
      }
    }

    /// <summary>Field number for the "TsMillis" field.</summary>
    public const int TsMillisFieldNumber = 7;
    private ulong tsMillis_;
    /// <summary>
    /// 时间戳(毫秒)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong TsMillis {
      get { return tsMillis_; }
      set {
        tsMillis_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ItemStatusUpdate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ItemStatusUpdate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UpdateType != other.UpdateType) return false;
      if (!object.Equals(Info, other.Info)) return false;
      if (!object.Equals(MovementStatus, other.MovementStatus)) return false;
      if (SceneID != other.SceneID) return false;
      if (State != other.State) return false;
      if (OwnerUID != other.OwnerUID) return false;
      if (TsMillis != other.TsMillis) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UpdateType != global::Net.Proto.ItemStatusUpdate.Types.ItemUpdateType.Spawn) hash ^= UpdateType.GetHashCode();
      if (info_ != null) hash ^= Info.GetHashCode();
      if (movementStatus_ != null) hash ^= MovementStatus.GetHashCode();
      if (SceneID != 0) hash ^= SceneID.GetHashCode();
      if (State != global::Net.Proto.ItemStatusUpdate.Types.ItemState.Idle) hash ^= State.GetHashCode();
      if (OwnerUID != 0) hash ^= OwnerUID.GetHashCode();
      if (TsMillis != 0UL) hash ^= TsMillis.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UpdateType != global::Net.Proto.ItemStatusUpdate.Types.ItemUpdateType.Spawn) {
        output.WriteRawTag(8);
        output.WriteEnum((int) UpdateType);
      }
      if (info_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Info);
      }
      if (movementStatus_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(MovementStatus);
      }
      if (SceneID != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(SceneID);
      }
      if (State != global::Net.Proto.ItemStatusUpdate.Types.ItemState.Idle) {
        output.WriteRawTag(40);
        output.WriteEnum((int) State);
      }
      if (OwnerUID != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(OwnerUID);
      }
      if (TsMillis != 0UL) {
        output.WriteRawTag(56);
        output.WriteUInt64(TsMillis);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UpdateType != global::Net.Proto.ItemStatusUpdate.Types.ItemUpdateType.Spawn) {
        output.WriteRawTag(8);
        output.WriteEnum((int) UpdateType);
      }
      if (info_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Info);
      }
      if (movementStatus_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(MovementStatus);
      }
      if (SceneID != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(SceneID);
      }
      if (State != global::Net.Proto.ItemStatusUpdate.Types.ItemState.Idle) {
        output.WriteRawTag(40);
        output.WriteEnum((int) State);
      }
      if (OwnerUID != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(OwnerUID);
      }
      if (TsMillis != 0UL) {
        output.WriteRawTag(56);
        output.WriteUInt64(TsMillis);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UpdateType != global::Net.Proto.ItemStatusUpdate.Types.ItemUpdateType.Spawn) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) UpdateType);
      }
      if (info_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Info);
      }
      if (movementStatus_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MovementStatus);
      }
      if (SceneID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SceneID);
      }
      if (State != global::Net.Proto.ItemStatusUpdate.Types.ItemState.Idle) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) State);
      }
      if (OwnerUID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(OwnerUID);
      }
      if (TsMillis != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TsMillis);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ItemStatusUpdate other) {
      if (other == null) {
        return;
      }
      if (other.UpdateType != global::Net.Proto.ItemStatusUpdate.Types.ItemUpdateType.Spawn) {
        UpdateType = other.UpdateType;
      }
      if (other.info_ != null) {
        if (info_ == null) {
          Info = new global::Net.Proto.ItemBasicInfo();
        }
        Info.MergeFrom(other.Info);
      }
      if (other.movementStatus_ != null) {
        if (movementStatus_ == null) {
          MovementStatus = new global::Net.Proto.BasicMovementStatus();
        }
        MovementStatus.MergeFrom(other.MovementStatus);
      }
      if (other.SceneID != 0) {
        SceneID = other.SceneID;
      }
      if (other.State != global::Net.Proto.ItemStatusUpdate.Types.ItemState.Idle) {
        State = other.State;
      }
      if (other.OwnerUID != 0) {
        OwnerUID = other.OwnerUID;
      }
      if (other.TsMillis != 0UL) {
        TsMillis = other.TsMillis;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            UpdateType = (global::Net.Proto.ItemStatusUpdate.Types.ItemUpdateType) input.ReadEnum();
            break;
          }
          case 18: {
            if (info_ == null) {
              Info = new global::Net.Proto.ItemBasicInfo();
            }
            input.ReadMessage(Info);
            break;
          }
          case 26: {
            if (movementStatus_ == null) {
              MovementStatus = new global::Net.Proto.BasicMovementStatus();
            }
            input.ReadMessage(MovementStatus);
            break;
          }
          case 32: {
            SceneID = input.ReadInt32();
            break;
          }
          case 40: {
            State = (global::Net.Proto.ItemStatusUpdate.Types.ItemState) input.ReadEnum();
            break;
          }
          case 48: {
            OwnerUID = input.ReadUInt32();
            break;
          }
          case 56: {
            TsMillis = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            UpdateType = (global::Net.Proto.ItemStatusUpdate.Types.ItemUpdateType) input.ReadEnum();
            break;
          }
          case 18: {
            if (info_ == null) {
              Info = new global::Net.Proto.ItemBasicInfo();
            }
            input.ReadMessage(Info);
            break;
          }
          case 26: {
            if (movementStatus_ == null) {
              MovementStatus = new global::Net.Proto.BasicMovementStatus();
            }
            input.ReadMessage(MovementStatus);
            break;
          }
          case 32: {
            SceneID = input.ReadInt32();
            break;
          }
          case 40: {
            State = (global::Net.Proto.ItemStatusUpdate.Types.ItemState) input.ReadEnum();
            break;
          }
          case 48: {
            OwnerUID = input.ReadUInt32();
            break;
          }
          case 56: {
            TsMillis = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ItemStatusUpdate message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// 物件状态（Idle/Active/Picked/Disabled 等）
      /// </summary>
      public enum ItemState {
        [pbr::OriginalName("Idle")] Idle = 0,
        [pbr::OriginalName("Active")] Active = 1,
        [pbr::OriginalName("Picked")] Picked = 2,
        [pbr::OriginalName("Disabled")] Disabled = 3,
      }

      public enum ItemUpdateType {
        [pbr::OriginalName("Spawn")] Spawn = 0,
        [pbr::OriginalName("Destroy")] Destroy = 1,
        [pbr::OriginalName("Move")] Move = 2,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
