// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: LevelProgressUpdate.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Net.Proto {

  /// <summary>Holder for reflection information generated from LevelProgressUpdate.proto</summary>
  public static partial class LevelProgressUpdateReflection {

    #region Descriptor
    /// <summary>File descriptor for LevelProgressUpdate.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LevelProgressUpdateReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlMZXZlbFByb2dyZXNzVXBkYXRlLnByb3RvEgJwYiJnChNMZXZlbFByb2dy",
            "ZXNzVXBkYXRlEg8KB1NjZW5lSUQYASABKAUSFAoMRmluaXNoZWRVSURzGAIg",
            "AygNEhQKDFRvdGFsUGxheWVycxgDIAEoDRITCgtOZXh0U2NlbmVJRBgEIAEo",
            "BUISWgQvY21kqgIJTmV0LlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Net.Proto.LevelProgressUpdate), global::Net.Proto.LevelProgressUpdate.Parser, new[]{ "SceneID", "FinishedUIDs", "TotalPlayers", "NextSceneID" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class LevelProgressUpdate : pb::IMessage<LevelProgressUpdate>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LevelProgressUpdate> _parser = new pb::MessageParser<LevelProgressUpdate>(() => new LevelProgressUpdate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LevelProgressUpdate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Net.Proto.LevelProgressUpdateReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LevelProgressUpdate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LevelProgressUpdate(LevelProgressUpdate other) : this() {
      sceneID_ = other.sceneID_;
      finishedUIDs_ = other.finishedUIDs_.Clone();
      totalPlayers_ = other.totalPlayers_;
      nextSceneID_ = other.nextSceneID_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LevelProgressUpdate Clone() {
      return new LevelProgressUpdate(this);
    }

    /// <summary>Field number for the "SceneID" field.</summary>
    public const int SceneIDFieldNumber = 1;
    private int sceneID_;
    /// <summary>
    /// 当前关卡 SceneID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SceneID {
      get { return sceneID_; }
      set {
        sceneID_ = value;
      }
    }

    /// <summary>Field number for the "FinishedUIDs" field.</summary>
    public const int FinishedUIDsFieldNumber = 2;
    private static readonly pb::FieldCodec<uint> _repeated_finishedUIDs_codec
        = pb::FieldCodec.ForUInt32(18);
    private readonly pbc::RepeatedField<uint> finishedUIDs_ = new pbc::RepeatedField<uint>();
    /// <summary>
    /// 已到达终点的玩家UID列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> FinishedUIDs {
      get { return finishedUIDs_; }
    }

    /// <summary>Field number for the "TotalPlayers" field.</summary>
    public const int TotalPlayersFieldNumber = 3;
    private uint totalPlayers_;
    /// <summary>
    /// 当前关卡内的总玩家数（统计口径以服务器为准）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TotalPlayers {
      get { return totalPlayers_; }
      set {
        totalPlayers_ = value;
      }
    }

    /// <summary>Field number for the "NextSceneID" field.</summary>
    public const int NextSceneIDFieldNumber = 4;
    private int nextSceneID_;
    /// <summary>
    /// 可选：下一关 SceneID（若已满足条件）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NextSceneID {
      get { return nextSceneID_; }
      set {
        nextSceneID_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LevelProgressUpdate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LevelProgressUpdate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SceneID != other.SceneID) return false;
      if(!finishedUIDs_.Equals(other.finishedUIDs_)) return false;
      if (TotalPlayers != other.TotalPlayers) return false;
      if (NextSceneID != other.NextSceneID) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SceneID != 0) hash ^= SceneID.GetHashCode();
      hash ^= finishedUIDs_.GetHashCode();
      if (TotalPlayers != 0) hash ^= TotalPlayers.GetHashCode();
      if (NextSceneID != 0) hash ^= NextSceneID.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SceneID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SceneID);
      }
      finishedUIDs_.WriteTo(output, _repeated_finishedUIDs_codec);
      if (TotalPlayers != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(TotalPlayers);
      }
      if (NextSceneID != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(NextSceneID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SceneID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SceneID);
      }
      finishedUIDs_.WriteTo(ref output, _repeated_finishedUIDs_codec);
      if (TotalPlayers != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(TotalPlayers);
      }
      if (NextSceneID != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(NextSceneID);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SceneID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SceneID);
      }
      size += finishedUIDs_.CalculateSize(_repeated_finishedUIDs_codec);
      if (TotalPlayers != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TotalPlayers);
      }
      if (NextSceneID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NextSceneID);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LevelProgressUpdate other) {
      if (other == null) {
        return;
      }
      if (other.SceneID != 0) {
        SceneID = other.SceneID;
      }
      finishedUIDs_.Add(other.finishedUIDs_);
      if (other.TotalPlayers != 0) {
        TotalPlayers = other.TotalPlayers;
      }
      if (other.NextSceneID != 0) {
        NextSceneID = other.NextSceneID;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SceneID = input.ReadInt32();
            break;
          }
          case 18:
          case 16: {
            finishedUIDs_.AddEntriesFrom(input, _repeated_finishedUIDs_codec);
            break;
          }
          case 24: {
            TotalPlayers = input.ReadUInt32();
            break;
          }
          case 32: {
            NextSceneID = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SceneID = input.ReadInt32();
            break;
          }
          case 18:
          case 16: {
            finishedUIDs_.AddEntriesFrom(ref input, _repeated_finishedUIDs_codec);
            break;
          }
          case 24: {
            TotalPlayers = input.ReadUInt32();
            break;
          }
          case 32: {
            NextSceneID = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
