// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Packet.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Net.Proto {

  /// <summary>Holder for reflection information generated from Packet.proto</summary>
  public static partial class PacketReflection {

    #region Descriptor
    /// <summary>File descriptor for Packet.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PacketReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxQYWNrZXQucHJvdG8SAnBiImIKBlBhY2tldBIRCglTZXNzaW9uSUQYASAB",
            "KAkSDQoFQ21kSUQYAiABKA0SDgoGQ21kTGVuGAMgASgNEgsKA01zZxgEIAEo",
            "DBIZChFTZW5kVGltZVN0YW1wTWlsbBgFIAEoBEISWgQvY21kqgIJTmV0LlBy",
            "b3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Net.Proto.Packet), global::Net.Proto.Packet.Parser, new[]{ "SessionID", "CmdID", "CmdLen", "Msg", "SendTimeStampMill" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Packet : pb::IMessage<Packet>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Packet> _parser = new pb::MessageParser<Packet>(() => new Packet());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Packet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Net.Proto.PacketReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Packet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Packet(Packet other) : this() {
      sessionID_ = other.sessionID_;
      cmdID_ = other.cmdID_;
      cmdLen_ = other.cmdLen_;
      msg_ = other.msg_;
      sendTimeStampMill_ = other.sendTimeStampMill_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Packet Clone() {
      return new Packet(this);
    }

    /// <summary>Field number for the "SessionID" field.</summary>
    public const int SessionIDFieldNumber = 1;
    private string sessionID_ = "";
    /// <summary>
    ///会话ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SessionID {
      get { return sessionID_; }
      set {
        sessionID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "CmdID" field.</summary>
    public const int CmdIDFieldNumber = 2;
    private uint cmdID_;
    /// <summary>
    ///指令ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CmdID {
      get { return cmdID_; }
      set {
        cmdID_ = value;
      }
    }

    /// <summary>Field number for the "CmdLen" field.</summary>
    public const int CmdLenFieldNumber = 3;
    private uint cmdLen_;
    /// <summary>
    ///指令长度
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CmdLen {
      get { return cmdLen_; }
      set {
        cmdLen_ = value;
      }
    }

    /// <summary>Field number for the "Msg" field.</summary>
    public const int MsgFieldNumber = 4;
    private pb::ByteString msg_ = pb::ByteString.Empty;
    /// <summary>
    ///指令主体(字节)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Msg {
      get { return msg_; }
      set {
        msg_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "SendTimeStampMill" field.</summary>
    public const int SendTimeStampMillFieldNumber = 5;
    private ulong sendTimeStampMill_;
    /// <summary>
    ///发送的时间戳(毫秒Mill)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong SendTimeStampMill {
      get { return sendTimeStampMill_; }
      set {
        sendTimeStampMill_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Packet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Packet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SessionID != other.SessionID) return false;
      if (CmdID != other.CmdID) return false;
      if (CmdLen != other.CmdLen) return false;
      if (Msg != other.Msg) return false;
      if (SendTimeStampMill != other.SendTimeStampMill) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SessionID.Length != 0) hash ^= SessionID.GetHashCode();
      if (CmdID != 0) hash ^= CmdID.GetHashCode();
      if (CmdLen != 0) hash ^= CmdLen.GetHashCode();
      if (Msg.Length != 0) hash ^= Msg.GetHashCode();
      if (SendTimeStampMill != 0UL) hash ^= SendTimeStampMill.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SessionID.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SessionID);
      }
      if (CmdID != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(CmdID);
      }
      if (CmdLen != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(CmdLen);
      }
      if (Msg.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Msg);
      }
      if (SendTimeStampMill != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(SendTimeStampMill);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SessionID.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SessionID);
      }
      if (CmdID != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(CmdID);
      }
      if (CmdLen != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(CmdLen);
      }
      if (Msg.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Msg);
      }
      if (SendTimeStampMill != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(SendTimeStampMill);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SessionID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SessionID);
      }
      if (CmdID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CmdID);
      }
      if (CmdLen != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CmdLen);
      }
      if (Msg.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Msg);
      }
      if (SendTimeStampMill != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(SendTimeStampMill);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Packet other) {
      if (other == null) {
        return;
      }
      if (other.SessionID.Length != 0) {
        SessionID = other.SessionID;
      }
      if (other.CmdID != 0) {
        CmdID = other.CmdID;
      }
      if (other.CmdLen != 0) {
        CmdLen = other.CmdLen;
      }
      if (other.Msg.Length != 0) {
        Msg = other.Msg;
      }
      if (other.SendTimeStampMill != 0UL) {
        SendTimeStampMill = other.SendTimeStampMill;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            SessionID = input.ReadString();
            break;
          }
          case 16: {
            CmdID = input.ReadUInt32();
            break;
          }
          case 24: {
            CmdLen = input.ReadUInt32();
            break;
          }
          case 34: {
            Msg = input.ReadBytes();
            break;
          }
          case 40: {
            SendTimeStampMill = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            SessionID = input.ReadString();
            break;
          }
          case 16: {
            CmdID = input.ReadUInt32();
            break;
          }
          case 24: {
            CmdLen = input.ReadUInt32();
            break;
          }
          case 34: {
            Msg = input.ReadBytes();
            break;
          }
          case 40: {
            SendTimeStampMill = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
