// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PlayerStatusUpdate.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Net.Proto {

  /// <summary>Holder for reflection information generated from PlayerStatusUpdate.proto</summary>
  public static partial class PlayerStatusUpdateReflection {

    #region Descriptor
    /// <summary>File descriptor for PlayerStatusUpdate.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlayerStatusUpdateReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhQbGF5ZXJTdGF0dXNVcGRhdGUucHJvdG8SAnBiGgxEZWZpbmUucHJvdG8i",
            "mgEKElBsYXllclN0YXR1c1VwZGF0ZRILCgNVSUQYASABKA0SDAoETmFtZRgC",
            "IAEoCRIvCg5Nb3ZlbWVudFN0YXR1cxgDIAEoCzIXLnBiLkJhc2ljTW92ZW1l",
            "bnRTdGF0dXMSDgoGRnJlZXplGAUgASgIEg8KB1NjZW5lSUQYBiABKAUSFwoP",
            "SXRlbVBpY2tlZENvdW50GAcgASgFQhJaBC9jbWSqAglOZXQuUHJvdG9iBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Net.Proto.DefineReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Net.Proto.PlayerStatusUpdate), global::Net.Proto.PlayerStatusUpdate.Parser, new[]{ "UID", "Name", "MovementStatus", "Freeze", "SceneID", "ItemPickedCount" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PlayerStatusUpdate : pb::IMessage<PlayerStatusUpdate>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerStatusUpdate> _parser = new pb::MessageParser<PlayerStatusUpdate>(() => new PlayerStatusUpdate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayerStatusUpdate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Net.Proto.PlayerStatusUpdateReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerStatusUpdate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerStatusUpdate(PlayerStatusUpdate other) : this() {
      uID_ = other.uID_;
      name_ = other.name_;
      movementStatus_ = other.movementStatus_ != null ? other.movementStatus_.Clone() : null;
      freeze_ = other.freeze_;
      sceneID_ = other.sceneID_;
      itemPickedCount_ = other.itemPickedCount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerStatusUpdate Clone() {
      return new PlayerStatusUpdate(this);
    }

    /// <summary>Field number for the "UID" field.</summary>
    public const int UIDFieldNumber = 1;
    private uint uID_;
    /// <summary>
    ///基本信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint UID {
      get { return uID_; }
      set {
        uID_ = value;
      }
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "MovementStatus" field.</summary>
    public const int MovementStatusFieldNumber = 3;
    private global::Net.Proto.BasicMovementStatus movementStatus_;
    /// <summary>
    ///运动、位置信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Net.Proto.BasicMovementStatus MovementStatus {
      get { return movementStatus_; }
      set {
        movementStatus_ = value;
      }
    }

    /// <summary>Field number for the "Freeze" field.</summary>
    public const int FreezeFieldNumber = 5;
    private bool freeze_;
    /// <summary>
    ///是否冻结
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Freeze {
      get { return freeze_; }
      set {
        freeze_ = value;
      }
    }

    /// <summary>Field number for the "SceneID" field.</summary>
    public const int SceneIDFieldNumber = 6;
    private int sceneID_;
    /// <summary>
    ///游戏进度
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SceneID {
      get { return sceneID_; }
      set {
        sceneID_ = value;
      }
    }

    /// <summary>Field number for the "ItemPickedCount" field.</summary>
    public const int ItemPickedCountFieldNumber = 7;
    private int itemPickedCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ItemPickedCount {
      get { return itemPickedCount_; }
      set {
        itemPickedCount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayerStatusUpdate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayerStatusUpdate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UID != other.UID) return false;
      if (Name != other.Name) return false;
      if (!object.Equals(MovementStatus, other.MovementStatus)) return false;
      if (Freeze != other.Freeze) return false;
      if (SceneID != other.SceneID) return false;
      if (ItemPickedCount != other.ItemPickedCount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UID != 0) hash ^= UID.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (movementStatus_ != null) hash ^= MovementStatus.GetHashCode();
      if (Freeze != false) hash ^= Freeze.GetHashCode();
      if (SceneID != 0) hash ^= SceneID.GetHashCode();
      if (ItemPickedCount != 0) hash ^= ItemPickedCount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UID != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(UID);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (movementStatus_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(MovementStatus);
      }
      if (Freeze != false) {
        output.WriteRawTag(40);
        output.WriteBool(Freeze);
      }
      if (SceneID != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(SceneID);
      }
      if (ItemPickedCount != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(ItemPickedCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UID != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(UID);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (movementStatus_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(MovementStatus);
      }
      if (Freeze != false) {
        output.WriteRawTag(40);
        output.WriteBool(Freeze);
      }
      if (SceneID != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(SceneID);
      }
      if (ItemPickedCount != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(ItemPickedCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UID);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (movementStatus_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MovementStatus);
      }
      if (Freeze != false) {
        size += 1 + 1;
      }
      if (SceneID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SceneID);
      }
      if (ItemPickedCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemPickedCount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayerStatusUpdate other) {
      if (other == null) {
        return;
      }
      if (other.UID != 0) {
        UID = other.UID;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.movementStatus_ != null) {
        if (movementStatus_ == null) {
          MovementStatus = new global::Net.Proto.BasicMovementStatus();
        }
        MovementStatus.MergeFrom(other.MovementStatus);
      }
      if (other.Freeze != false) {
        Freeze = other.Freeze;
      }
      if (other.SceneID != 0) {
        SceneID = other.SceneID;
      }
      if (other.ItemPickedCount != 0) {
        ItemPickedCount = other.ItemPickedCount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            UID = input.ReadUInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            if (movementStatus_ == null) {
              MovementStatus = new global::Net.Proto.BasicMovementStatus();
            }
            input.ReadMessage(MovementStatus);
            break;
          }
          case 40: {
            Freeze = input.ReadBool();
            break;
          }
          case 48: {
            SceneID = input.ReadInt32();
            break;
          }
          case 56: {
            ItemPickedCount = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            UID = input.ReadUInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            if (movementStatus_ == null) {
              MovementStatus = new global::Net.Proto.BasicMovementStatus();
            }
            input.ReadMessage(MovementStatus);
            break;
          }
          case 40: {
            Freeze = input.ReadBool();
            break;
          }
          case 48: {
            SceneID = input.ReadInt32();
            break;
          }
          case 56: {
            ItemPickedCount = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
