// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PlayerOpEvent.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Net.Proto {

  /// <summary>Holder for reflection information generated from PlayerOpEvent.proto</summary>
  public static partial class PlayerOpEventReflection {

    #region Descriptor
    /// <summary>File descriptor for PlayerOpEvent.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlayerOpEventReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNQbGF5ZXJPcEV2ZW50LnByb3RvEgJwYiK1AQoNUGxheWVyT3BFdmVudBIM",
            "CgRuYW1lGAEgASgJEiYKBHR5cGUYAiABKA4yGC5wYi5QbGF5ZXJPcEV2ZW50",
            "Lk9wVHlwZRIMCgRkaXJYGAMgASgCEg8KB3ByZXNzTXMYBCABKA0SEAoIdHNN",
            "aWxsaXMYBSABKAQiPQoGT3BUeXBlEg0KCU1vdmVTdGFydBAAEgwKCE1vdmVI",
            "b2xkEAESDAoITW92ZVN0b3AQAhIICgRKdW1wEANCEloEL2NtZKoCCU5ldC5Q",
            "cm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Net.Proto.PlayerOpEvent), global::Net.Proto.PlayerOpEvent.Parser, new[]{ "Name", "Type", "DirX", "PressMs", "TsMillis" }, null, new[]{ typeof(global::Net.Proto.PlayerOpEvent.Types.OpType) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// 玩家操作事件，用于实时广播输入操作
  /// </summary>
  public sealed partial class PlayerOpEvent : pb::IMessage<PlayerOpEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PlayerOpEvent> _parser = new pb::MessageParser<PlayerOpEvent>(() => new PlayerOpEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PlayerOpEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Net.Proto.PlayerOpEventReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerOpEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerOpEvent(PlayerOpEvent other) : this() {
      name_ = other.name_;
      type_ = other.type_;
      dirX_ = other.dirX_;
      pressMs_ = other.pressMs_;
      tsMillis_ = other.tsMillis_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PlayerOpEvent Clone() {
      return new PlayerOpEvent(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    /// <summary>
    /// 玩家唯一标识（可用 Name 或 UID，与你们现有定义一致即可）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 2;
    private global::Net.Proto.PlayerOpEvent.Types.OpType type_ = global::Net.Proto.PlayerOpEvent.Types.OpType.MoveStart;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Net.Proto.PlayerOpEvent.Types.OpType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "dirX" field.</summary>
    public const int DirXFieldNumber = 3;
    private float dirX_;
    /// <summary>
    /// 水平方向：-1 表示左，+1 表示右，0 表示停止
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float DirX {
      get { return dirX_; }
      set {
        dirX_ = value;
      }
    }

    /// <summary>Field number for the "pressMs" field.</summary>
    public const int PressMsFieldNumber = 4;
    private uint pressMs_;
    /// <summary>
    /// 按键保持的时长（毫秒），用于 MoveHold，辅助远端对齐节奏
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PressMs {
      get { return pressMs_; }
      set {
        pressMs_ = value;
      }
    }

    /// <summary>Field number for the "tsMillis" field.</summary>
    public const int TsMillisFieldNumber = 5;
    private ulong tsMillis_;
    /// <summary>
    /// 事件时间戳（毫秒，Unix epoch）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong TsMillis {
      get { return tsMillis_; }
      set {
        tsMillis_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PlayerOpEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PlayerOpEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Type != other.Type) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(DirX, other.DirX)) return false;
      if (PressMs != other.PressMs) return false;
      if (TsMillis != other.TsMillis) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Type != global::Net.Proto.PlayerOpEvent.Types.OpType.MoveStart) hash ^= Type.GetHashCode();
      if (DirX != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(DirX);
      if (PressMs != 0) hash ^= PressMs.GetHashCode();
      if (TsMillis != 0UL) hash ^= TsMillis.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Type != global::Net.Proto.PlayerOpEvent.Types.OpType.MoveStart) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (DirX != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(DirX);
      }
      if (PressMs != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(PressMs);
      }
      if (TsMillis != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(TsMillis);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Type != global::Net.Proto.PlayerOpEvent.Types.OpType.MoveStart) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Type);
      }
      if (DirX != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(DirX);
      }
      if (PressMs != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(PressMs);
      }
      if (TsMillis != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(TsMillis);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Type != global::Net.Proto.PlayerOpEvent.Types.OpType.MoveStart) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (DirX != 0F) {
        size += 1 + 4;
      }
      if (PressMs != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PressMs);
      }
      if (TsMillis != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TsMillis);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PlayerOpEvent other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Type != global::Net.Proto.PlayerOpEvent.Types.OpType.MoveStart) {
        Type = other.Type;
      }
      if (other.DirX != 0F) {
        DirX = other.DirX;
      }
      if (other.PressMs != 0) {
        PressMs = other.PressMs;
      }
      if (other.TsMillis != 0UL) {
        TsMillis = other.TsMillis;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Type = (global::Net.Proto.PlayerOpEvent.Types.OpType) input.ReadEnum();
            break;
          }
          case 29: {
            DirX = input.ReadFloat();
            break;
          }
          case 32: {
            PressMs = input.ReadUInt32();
            break;
          }
          case 40: {
            TsMillis = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Type = (global::Net.Proto.PlayerOpEvent.Types.OpType) input.ReadEnum();
            break;
          }
          case 29: {
            DirX = input.ReadFloat();
            break;
          }
          case 32: {
            PressMs = input.ReadUInt32();
            break;
          }
          case 40: {
            TsMillis = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the PlayerOpEvent message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// 操作类型
      /// </summary>
      public enum OpType {
        /// <summary>
        /// 开始移动（按下方向键）
        /// </summary>
        [pbr::OriginalName("MoveStart")] MoveStart = 0,
        /// <summary>
        /// 移动长按（周期性重发，保证远端持续移动）
        /// </summary>
        [pbr::OriginalName("MoveHold")] MoveHold = 1,
        /// <summary>
        /// 停止移动（松开方向键）
        /// </summary>
        [pbr::OriginalName("MoveStop")] MoveStop = 2,
        /// <summary>
        /// 跳跃（按下 Space）
        /// </summary>
        [pbr::OriginalName("Jump")] Jump = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
