// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SceneDataResp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Net.Proto {

  /// <summary>Holder for reflection information generated from SceneDataResp.proto</summary>
  public static partial class SceneDataRespReflection {

    #region Descriptor
    /// <summary>File descriptor for SceneDataResp.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SceneDataRespReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNTY2VuZURhdGFSZXNwLnByb3RvEgJwYiJsCg1TY2VuZURhdGFSZXNwEg8K",
            "B0xldmVsSUQYASABKAkSDwoHU2NlbmVJRBgCIAEoBRIRCglMZXZlbE5hbWUY",
            "AyABKAkSEwoLQ2hlcnJ5Q291bnQYBCABKAUSEQoJU2NlbmVUeXBlGAUgASgJ",
            "QhJaBC9jbWSqAglOZXQuUHJvdG9iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Net.Proto.SceneDataResp), global::Net.Proto.SceneDataResp.Parser, new[]{ "LevelID", "SceneID", "LevelName", "CherryCount", "SceneType" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SceneDataResp : pb::IMessage<SceneDataResp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SceneDataResp> _parser = new pb::MessageParser<SceneDataResp>(() => new SceneDataResp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SceneDataResp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Net.Proto.SceneDataRespReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SceneDataResp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SceneDataResp(SceneDataResp other) : this() {
      levelID_ = other.levelID_;
      sceneID_ = other.sceneID_;
      levelName_ = other.levelName_;
      cherryCount_ = other.cherryCount_;
      sceneType_ = other.sceneType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SceneDataResp Clone() {
      return new SceneDataResp(this);
    }

    /// <summary>Field number for the "LevelID" field.</summary>
    public const int LevelIDFieldNumber = 1;
    private string levelID_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LevelID {
      get { return levelID_; }
      set {
        levelID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "SceneID" field.</summary>
    public const int SceneIDFieldNumber = 2;
    private int sceneID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SceneID {
      get { return sceneID_; }
      set {
        sceneID_ = value;
      }
    }

    /// <summary>Field number for the "LevelName" field.</summary>
    public const int LevelNameFieldNumber = 3;
    private string levelName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LevelName {
      get { return levelName_; }
      set {
        levelName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "CherryCount" field.</summary>
    public const int CherryCountFieldNumber = 4;
    private int cherryCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CherryCount {
      get { return cherryCount_; }
      set {
        cherryCount_ = value;
      }
    }

    /// <summary>Field number for the "SceneType" field.</summary>
    public const int SceneTypeFieldNumber = 5;
    private string sceneType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SceneType {
      get { return sceneType_; }
      set {
        sceneType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SceneDataResp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SceneDataResp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (LevelID != other.LevelID) return false;
      if (SceneID != other.SceneID) return false;
      if (LevelName != other.LevelName) return false;
      if (CherryCount != other.CherryCount) return false;
      if (SceneType != other.SceneType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (LevelID.Length != 0) hash ^= LevelID.GetHashCode();
      if (SceneID != 0) hash ^= SceneID.GetHashCode();
      if (LevelName.Length != 0) hash ^= LevelName.GetHashCode();
      if (CherryCount != 0) hash ^= CherryCount.GetHashCode();
      if (SceneType.Length != 0) hash ^= SceneType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (LevelID.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(LevelID);
      }
      if (SceneID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(SceneID);
      }
      if (LevelName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(LevelName);
      }
      if (CherryCount != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(CherryCount);
      }
      if (SceneType.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(SceneType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (LevelID.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(LevelID);
      }
      if (SceneID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(SceneID);
      }
      if (LevelName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(LevelName);
      }
      if (CherryCount != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(CherryCount);
      }
      if (SceneType.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(SceneType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (LevelID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LevelID);
      }
      if (SceneID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SceneID);
      }
      if (LevelName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LevelName);
      }
      if (CherryCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CherryCount);
      }
      if (SceneType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SceneType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SceneDataResp other) {
      if (other == null) {
        return;
      }
      if (other.LevelID.Length != 0) {
        LevelID = other.LevelID;
      }
      if (other.SceneID != 0) {
        SceneID = other.SceneID;
      }
      if (other.LevelName.Length != 0) {
        LevelName = other.LevelName;
      }
      if (other.CherryCount != 0) {
        CherryCount = other.CherryCount;
      }
      if (other.SceneType.Length != 0) {
        SceneType = other.SceneType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            LevelID = input.ReadString();
            break;
          }
          case 16: {
            SceneID = input.ReadInt32();
            break;
          }
          case 26: {
            LevelName = input.ReadString();
            break;
          }
          case 32: {
            CherryCount = input.ReadInt32();
            break;
          }
          case 42: {
            SceneType = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            LevelID = input.ReadString();
            break;
          }
          case 16: {
            SceneID = input.ReadInt32();
            break;
          }
          case 26: {
            LevelName = input.ReadString();
            break;
          }
          case 32: {
            CherryCount = input.ReadInt32();
            break;
          }
          case 42: {
            SceneType = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
